version: "3.1"
services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "9999:3306"
      - "9998:33060"
    volumes:
      - ./dir:/dir:z
      - ./volume:/var/lib/mysql:z
